ID: azure_compute_vm_adaptive_application_controls_enabled
Title: Adaptive application controls for defining safe applications should be enabled on your machines
Description: Enable application controls to define the list of known-safe applications running on your machines, and alert you when other applications run. This helps harden your machines against malware. To simplify the process of configuring and maintaining your rules, Security Center uses machine learning to analyze the applications running on each machine and suggest the list of known-safe applications.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      id as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      'info' as status,
      'Manual verification required. Check control description for more details.' as reason,
      display_name as subscription
    from
      azure_subscription;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- azure
Tags: {}
Severity: low
