connectors:
- AWS
name: Elastic Beanstalk Web Application Service
query: select connection_id, region, count(*) from kaytu_lookup where resource_type = 'aws::elasticbeanstalk::application' group by 1,2;
status: active
tags:
  category:
  - PaaS
  search_terms:
  - Elastic Beanstalk
  - AWS Beanstalk
  - AWS web app
  - Beanstalk
  - AWS deployment
  - AWS PaaS
  - Web application
  - AWS application
  - AWS scalable app
  - Amazon Beanstalk
