connectors:
- Azure
name: Application security group (ASG)
query: select connection_id, region, count(*) from kaytu_lookup where resource_type = 'microsoft.network/applicationsecuritygroups' group by 1,2;
status: inactive
tags:
  category:
  - Network Security
