ID: aws_vpc_security_group_restrict_ingress_kafka_port
Title: VPC security groups should restrict ingress Kafka port access from 0.0.0.0/0
Description: AWS VPC security groups can help in managing network access by providing stateful filtering of ingress and egress network traffic to AWS resources.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    with ingress_kafka_port as (
      select
        group_id,
        count(*) as num_ssh_rules
      from
        aws_vpc_security_group_rule
      where
        type = 'ingress'
        and (
          cidr_ipv4 = '0.0.0.0/0'
          or cidr_ipv6 = '::/0'
        )
        and (
            ( ip_protocol = '-1'
            and from_port is null
            )
            or (
              from_port >= 9092
              and to_port <= 9092
            )
        )
      group by
        group_id
    )
    select
      arn as resource,
      sg.kaytu_account_id as kaytu_account_id,
      sg.kaytu_resource_id as kaytu_resource_id,
      case
        when k.group_id is null then 'ok'
        else 'alarm'
      end as status,
      case
        when k.group_id is null then sg.group_id || ' ingress restricted for kafka port from 0.0.0.0/0.'
        else sg.group_id || ' contains ' || k.num_ssh_rules || ' ingress rule(s) allowing kafka port from 0.0.0.0/0.'
      end as reason
    from
      aws_vpc_security_group as sg
      left join ingress_kafka_port as k on k.group_id = sg.group_id;
  PrimaryTable: aws_vpc_security_group
  ListOfTables:
  - aws_vpc_security_group_rule
  - aws_vpc_security_group
  Parameters: []
Connector:
- aws
Tags: {}
Severity: low
