ID: aws_enable_amazon_waf_integration_for_application_load_balancers
Title: Enable Amazon WAF Integration for Application Load Balancers
Description: Use Amazon WAF to protect Application Load Balancers from common web exploits.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    with associated_resource as (
      select
        arns
      from
        aws_wafv2_web_acl,
        jsonb_array_elements_text(associated_resources) as arns
    )
    select
      arn as resource,
      kaytu_resource_id,
      kaytu_account_id,
      case
        when ar.arns is not null then 'ok'
        else 'alarm'
      end as status,
      case
        when ar.arns is not null then title || ' WAF enabled.'
        else title || ' WAF disabled.'
      end as reason,
      region,
      account_id
    from
      aws_ec2_application_load_balancer as lb
      left join associated_resource as ar on lb.arn = ar.arns;
  Connector:
  - AWS
  PrimaryTable: aws_ec2_application_load_balancer
  ListOfTables:
  - aws_ec2_application_load_balancer
  - aws_wafv2_web_acl
  Parameters: []
  Global: false
ManualVerification: false
Severity: high
Tags:
  score_service_name:
  - AWS Elastic Load Balancing V2 (ELBv2)
  score_tags:
  - Exposed Endpoints
Managed: false
