ID: aws_baseline_supportability_iam_and_security
Title: "AWS Baseline Supportability - IAM and Security"
Description: "Ensure AWS IAM policies and security are configured for supportability."
AutoAssign: true
Controls:
  - aws_multi_account_centralized_management
  - aws_use_aws_managed_policy_to_access_amazon_ecr_repositories
  - aws_use_aws_managed_policy_to_manage_aws_resources
Enabled: true
SectionCode: aws_baseline_supportability_iam_and_security
Tags:
  baseline_category:
    - supportability
  type:
    - BASELINE
TracksDriftEvents: false