Description: To ensure the relevant people in your organization are notified when there is a potential security breach in one of your subscriptions, set a security contact to receive email notifications from Security Center.
ID: azure_securitycenter_email_configured
IntegrationType:
  - azure_subscription
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - azure_subscription
    - azure_security_center_contact
  Parameters: []
  PrimaryTable: azure_subscription
  QueryToExecute: |
    WITH contact_info AS (
      SELECT
        jsonb_agg(email) FILTER (WHERE name = 'default' AND email != '') AS default_email,
        COUNT(*) FILTER (WHERE name != 'default') AS non_default_count,
        COUNT(*) FILTER (WHERE name = 'default') AS default_count,
        subscription_id
      FROM
        azure_security_center_contact
      GROUP BY
        subscription_id
      LIMIT 1
    )
    SELECT
      sub.subscription_id AS resource,
      sub.platform_integration_id AS platform_integration_id,
      sub.platform_resource_id AS platform_resource_id,
      CASE
        WHEN non_default_count > 0 THEN 'ok'
        WHEN default_count = 1 AND jsonb_array_length(default_email) != 0 THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN non_default_count > 0 THEN 'Additional email addresses configured.'
        WHEN default_count = 1 AND default_email IS NOT NULL THEN 'Additional email addresses configured.'
        ELSE 'Additional email addresses not configured.'
      END AS reason,
      sub.display_name AS subscription
    FROM
      azure_subscription sub
    LEFT JOIN contact_info ci ON sub.subscription_id = ci.subscription_id
Severity: medium
Tags:
  nist_sp_800_53_rev_5:
    - "true"
  service:
    - Azure/SecurityCenter
Title: Subscriptions should have a contact email address for security issues