Description: Azure Private Link lets you connect your virtual network to Azure services without a public IP address at the source or destination. The private link platform handles the connectivity between the consumer and services over the Azure backbone network. By mapping private endpoints to your app configuration instances instead of the entire service, you'll also be protected against data leakage risks.
ID: azure_app_configuration_private_link_used
IntegrationType:
  - azure_subscription
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - azure_app_configuration
    - azure_subscription
  Parameters: []
  PrimaryTable: azure_app_configuration
  QueryToExecute: |
    SELECT
      a.id AS resource,
      a.platform_integration_id AS platform_integration_id,
      a.platform_resource_id AS platform_resource_id,
      CASE
        WHEN sku_name = 'free' THEN 'skip'
        WHEN public_network_access = 'Enabled' AND private_endpoint_connections IS NULL THEN 'alarm'
        WHEN private_endpoint_connections @> '[{"privateLinkServiceConnectionStateStatus": "Approved"}]'::jsonb THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN sku_name = 'free' THEN a.name || ' is of ' || sku_name || ' tier.'
        WHEN public_network_access = 'Enabled' AND private_endpoint_connections IS NULL THEN ' using public networks.'
        WHEN private_endpoint_connections @> '[{"privateLinkServiceConnectionStateStatus": "Approved"}]'::jsonb THEN a.name || ' using private link.'
        ELSE a.name || ' not using private link.'
      END AS reason,
      a.resource_group AS resource_group,
      sub.display_name AS subscription
    FROM
      azure_app_configuration AS a,
      azure_subscription AS sub;
Severity: medium
Tags:
  nist_sp_800_53_rev_5:
    - "true"
  service:
    - Azure/AppConfiguration
Title: App Configuration should use private link