Description: Protect your subnet from potential threats by restricting access to it with a Network Security Group (NSG). NSGs contain a list of Access Control List (ACL) rules that allow or deny network traffic to your subnet.
ID: azure_network_security_group_not_configured_gateway_subnets
IntegrationType:
  - azure_subscription
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - azure_subnet
    - azure_subscription
  Parameters: []
  PrimaryTable: azure_subnet
  QueryToExecute: |
    SELECT
      subnet.id AS resource,
      subnet.platform_account_id AS platform_account_id,
      subnet.platform_resource_id AS platform_resource_id,
      CASE
        WHEN subnet.name = 'GatewaySubnet' AND network_security_group_id IS NOT NULL THEN 'alarm'
        WHEN subnet.name = 'GatewaySubnet' AND network_security_group_id IS NULL THEN 'ok'
        ELSE 'skip'
      END AS status,
      CASE
        WHEN subnet.name = 'GatewaySubnet' AND network_security_group_id IS NOT NULL THEN 'Gateway subnet configured with network security group.'
        WHEN subnet.name = 'GatewaySubnet' AND network_security_group_id IS NULL THEN 'Gateway subnet not configured with network security group.'
        ELSE subnet.name || ' not of gateway subnet type.'
      END AS reason,
      subnet.resource_group AS resource_group,
      sub.display_name AS subscription
    FROM
      azure_subnet AS subnet
    JOIN
      azure_subscription AS sub ON sub.subscription_id = subnet.subscription_id;
Severity: high
Tags:
  hipaa_hitrust_v92:
    - "true"
  service:
    - Azure/Network
Title: Gateway subnets should not be configured with a network security group