Description: The Guest Configuration extension requires a system assigned managed identity. Azure virtual machines in the scope of this policy will be non-compliant when they have the Guest Configuration extension installed but do not have a system assigned managed identity.
ID: azure_compute_vm_guest_configuration_with_system_assigned_managed_identity
IntegrationType:
  - azure_subscription
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - azure_compute_virtual_machine
    - azure_subscription
  Parameters: []
  PrimaryTable: azure_compute_virtual_machine
  QueryToExecute: |
    WITH gc_installed_vm AS (
      SELECT
        DISTINCT a.vm_id,
        title
      FROM
        azure_compute_virtual_machine AS a,
        jsonb_array_elements(extensions) AS b
      WHERE
        b ->> 'Publisher' = 'Microsoft.GuestConfiguration'
    )
    SELECT
      a.vm_id AS resource,
      a.platform_integration_id AS platform_integration_id,
      a.platform_resource_id AS platform_resource_id,
      CASE
        WHEN b.vm_id IS NULL THEN 'skip'
        WHEN b.vm_id IS NOT NULL AND string_to_array(identity ->> 'type', ', ') @> ARRAY['SystemAssigned'] THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN b.vm_id IS NULL THEN a.title || ' guest configuration extension not installed.'
        WHEN b.vm_id IS NOT NULL AND string_to_array(identity ->> 'type', ', ') @> ARRAY['SystemAssigned'] THEN a.title || ' guest configuration extension installed with system-assigned managed identity.'
        ELSE a.title || ' guest configuration extension not installed with system-assigned managed identity.'
      END AS reason,
      a.resource_group AS resource_group,
      sub.display_name AS subscription
    FROM
      azure_compute_virtual_machine AS a
    LEFT JOIN gc_installed_vm AS b ON a.vm_id = b.vm_id,
      azure_subscription AS sub
    WHERE
      sub.subscription_id = a.subscription_id
Severity: medium
Tags:
  nist_sp_800_53_rev_5:
    - "true"
  service:
    - Azure/Compute
Title: Virtual machines' Guest Configuration extension should be deployed with system-assigned managed identity