Description: To ensure secure configurations of in-guest settings of your machine, install the Guest Configuration extension. In-guest settings that the extension monitors include the configuration of the operating system, application configuration or presence, and environment settings. Once installed, in-guest policies will be available such as 'Windows Exploit guard should be enabled'.
ID: azure_compute_vm_guest_configuration_installed
IntegrationType:
  - azure_subscription
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - azure_compute_virtual_machine
    - azure_subscription
  Parameters: []
  PrimaryTable: azure_compute_virtual_machine
  QueryToExecute: |
    WITH agent_installed_vm AS (
      SELECT
        DISTINCT a.vm_id
      FROM
        azure_compute_virtual_machine AS a,
        jsonb_array_elements(extensions) AS b
      WHERE
        b ->> 'Publisher' = 'Microsoft.GuestConfiguration'
        AND b ->> 'ProvisioningState' = 'Succeeded'
    )
    SELECT
      a.vm_id AS resource,
      a.og_account_id AS og_account_id,
      a.og_resource_id AS og_resource_id,
      CASE
        WHEN b.vm_id IS NOT NULL THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN b.vm_id IS NOT NULL THEN a.title || ' have guest configuration extension installed.'
        ELSE a.title || ' guest configuration extension not installed.'
      END AS reason,
      a.resource_group AS resource_group,
      sub.display_name AS subscription
    FROM
      azure_compute_virtual_machine AS a
      LEFT JOIN agent_installed_vm AS b ON a.vm_id = b.vm_id,
      azure_subscription AS sub
    WHERE
      sub.subscription_id = a.subscription_id;
Severity: medium
Tags:
  nist_sp_800_53_rev_5:
    - "true"
  service:
    - Azure/Compute
Title: Guest Configuration extension should be installed on your machines