Title: "Find AWS Route 53 Resolver Query Log Configurations"
Description: "Allows users to query AWS Route 53 Resolver Query Log Configurations."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      id,
      creation_time,
      destination_arn,
      status
    from
      aws_route53_resolver_query_log_config
    where
      creation_time >= now() - interval '30' day;
Tags:
  cloud_asset_management:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Route 53
