Title: "Find AWS EMR Block Public Access Configurations"
Description: "Allows users to query AWS EMR Block Public Access Configuration to retrieve details about the block public access configurations for EMR clusters."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      created_by_arn,
      creation_date,
      rules ->> 'MaxRange' as max_range,
      rules ->> 'MinRange' as min_range
    from
      aws_emr_block_public_access_configuration
      cross join jsonb_array_elements(permitted_public_security_group_rule_ranges) as rules;
Tags:
  cloud_asset_management:
  - "true"
  cloud_network_security:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - EMR Block Public Access Configuration
