Title: "List all AWS Config Rules with Proactive Evaluation Mode"
Description: "Allows users to query Config Rules in AWS Config service. It provides information about each Config Rule, including its name, ARN, description, scope, and compliance status."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name as config_rule_name,
      c ->> 'Mode' as evaluation_mode
    from
      aws_config_rule,
      jsonb_array_elements(evaluation_modes) as c
    where
      c ->> 'Mode' = 'PROACTIVE';
Tags:
  cloud_asset_management: true
  cloud_provider: aws
  cloud_service: Config Rules
