ID: aws_glue_data_catalog_encryption_settings_1
Title: "Find AWS Glue Data Catalog Encryption Settings"
Description: "Allows users to query AWS Glue Data Catalog Encryption Settings."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      encryption_at_rest,
      connection_password_encryption,
      region,
      account_id
    from
      aws_glue_data_catalog_encryption_settings;
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_asset_management:
  - "true"
  cloud_data_security:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - AWS Glue
