Title: "List All AWS EC2 Application Load Balancers with Details"
Description: "Allows users to query AWS EC2 Application Load Balancer, providing detailed information about each load balancer within an AWS account. This includes its current state, availability zones, security groups, and other important attributes."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      az ->> 'LoadBalancerAddresses' as load_balancer_addresses,
      az ->> 'OutpostId' as outpost_id,
      az ->> 'SubnetId' as subnet_id,
      az ->> 'ZoneName' as zone_name
    from
      aws_ec2_application_load_balancer
      cross join jsonb_array_elements(availability_zones) as az;
Tags:
  cloud_asset_management: true
  cloud_network_security: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: EC2 Application Load Balancer
