Title: "List all AWS Config Rules with Details"
Description: "Allows users to query Config Rules in AWS Config service. It provides information about each Config Rule, including its name, ARN, description, scope, and compliance status."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      rule_id,
      arn,
      rule_state,
      created_by,
      scope
    from
      aws_config_rule;
Tags:
  cloud_asset_management: true
  cloud_ops: true
  cloud_provider: aws
  cloud_service: Config
