Title: "Find AWS ECR Registry Scanning Configuration per Region"
Description: "Allows users to query AWS ECR Registry Scanning Configuration at the private registry level on a per-region basis."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      registry_id,
      jsonb_pretty(scanning_configuration),
      region
    from
      aws_ecr_registry_scanning_configuration
    where
      region = 'ap-south-1';
Tags:
  cloud_asset_management:
  - "true"
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - ECR
