Description: AWS VPC security groups can help in managing network access by providing stateful filtering of ingress and egress network traffic to AWS resources.
ID: aws_vpc_security_group_restrict_ingress_redis_port
IntegrationType:
  - aws_cloud_account
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - aws_vpc_security_group_rule
    - aws_vpc_security_group
  Parameters: []
  PrimaryTable: aws_vpc_security_group
  QueryToExecute: |
    WITH ingress_redis_port AS (
      SELECT
        group_id,
        COUNT(*) AS num_redis_rules
      FROM
        aws_vpc_security_group_rule
      WHERE
        type = 'ingress'
        AND (
          cidr_ipv4 = '0.0.0.0/0'
          OR cidr_ipv6 = '::/0'
        )
        AND (
          (ip_protocol = '-1' AND from_port IS NULL)
          OR (from_port >= 6379 AND to_port <= 6379)
        )
      GROUP BY
        group_id
    )
    SELECT
      arn AS resource,
      sg.platform_integration_id AS platform_integration_id,
      sg.platform_resource_id AS platform_resource_id,
      CASE
        WHEN ingress_redis_port.group_id IS NULL THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN ingress_redis_port.group_id IS NULL THEN sg.group_id || ' restricted ingress from 0.0.0.0/0 or ::/0 to Redis port 6379.'
        ELSE sg.group_id || ' contains ' || ingress_redis_port.num_redis_rules || ' ingress rule(s) from 0.0.0.0/0 or ::/0 to Redis port 6379.'
      END AS reason
    FROM
      aws_vpc_security_group AS sg
    LEFT JOIN ingress_redis_port ON ingress_redis_port.group_id = sg.group_id;
Severity: low
Tags: {}
Title: VPC security groups should restrict ingress redis access from 0.0.0.0/0