Description: Ensure authentication credentials AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY do not exist within AWS CodeBuild project environments. Do not store these variables in clear text. Storing these variables in clear text leads to unintended data exposure and unauthorized access.
ID: aws_codebuild_project_plaintext_env_variables_no_sensitive_aws_values
IntegrationType:
  - aws_cloud_account
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - aws_codebuild_project
  Parameters: []
  PrimaryTable: aws_codebuild_project
  QueryToExecute: |
    WITH invalid_key_name AS (
      SELECT DISTINCT
        arn,
        name
      FROM
        aws_codebuild_project,
        jsonb_array_elements(environment -> 'EnvironmentVariables') AS env
      WHERE
        env ->> 'Name' ILIKE ANY(ARRAY['%AWS_ACCESS_KEY_ID%', '%AWS_SECRET_ACCESS_KEY%', '%PASSWORD%'])
        AND env ->> 'Type' = 'PLAINTEXT'
    )
    SELECT
      a.arn AS resource,
      a.og_account_id AS og_account_id,
      a.og_resource_id AS og_resource_id,
      CASE
        WHEN b.arn IS NULL THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN b.arn IS NULL THEN a.title || ' has no plaintext environment variables with sensitive AWS values.'
        ELSE a.title || ' has plaintext environment variables with sensitive AWS values.'
      END AS reason,
      a.region,
      a.account_id
    FROM
      aws_codebuild_project AS a
      LEFT JOIN invalid_key_name b ON a.arn = b.arn;
Severity: high
Tags:
  category:
    - Compliance
  cis_controls_v8_ig1:
    - "true"
  cisa_cyber_essentials:
    - "true"
  fedramp_low_rev_4:
    - "true"
  fedramp_moderate_rev_4:
    - "true"
  ffiec:
    - "true"
  hipaa_final_omnibus_security_rule_2013:
    - "true"
  hipaa_security_rule_2003:
    - "true"
  nist_800_53_rev_4:
    - "true"
  nist_csf:
    - "true"
  pci_dss_v321:
    - "true"
  plugin:
    - aws
  service:
    - AWS/CodeBuild
  soc_2:
    - "true"
Title: CodeBuild project plaintext environment variables should not contain sensitive AWS values