Description: AWS VPC security groups can help in managing network access by providing stateful filtering of ingress and egress network traffic to AWS resources.
ID: aws_vpc_security_group_restrict_ingress_kafka_port
IntegrationType:
  - aws_cloud_account
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - aws_vpc_security_group_rule
    - aws_vpc_security_group
  Parameters: []
  PrimaryTable: aws_vpc_security_group
  QueryToExecute: |
    WITH ingress_kafka_port AS (
      SELECT
        group_id,
        COUNT(*) AS num_ssh_rules
      FROM
        aws_vpc_security_group_rule
      WHERE
        type = 'ingress'
        AND (
          cidr_ipv4 = '0.0.0.0/0'
          OR cidr_ipv6 = '::/0'
        )
        AND (
          (ip_protocol = '-1' AND from_port IS NULL)
          OR (
            from_port >= 9092
            AND to_port <= 9092
          )
        )
      GROUP BY
        group_id
    )
    SELECT
      arn AS resource,
      sg.platform_account_id AS platform_account_id,
      sg.platform_resource_id AS platform_resource_id,
      CASE
        WHEN k.group_id IS NULL THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN k.group_id IS NULL THEN sg.group_id || ' ingress restricted for kafka port from 0.0.0.0/0.'
        ELSE sg.group_id || ' contains ' || k.num_ssh_rules || ' ingress rule(s) allowing kafka port from 0.0.0.0/0.'
      END AS reason
    FROM
      aws_vpc_security_group AS sg
    LEFT JOIN ingress_kafka_port AS k 
      ON k.group_id = sg.group_id;
Severity: low
Tags: {}
Title: VPC security groups should restrict ingress Kafka port access from 0.0.0.0/0