Description: Ensure the GitHub or Bitbucket source repository URL does not contain personal access tokens, user name and password within AWS Codebuild project environments.
ID: aws_codebuild_project_source_repo_oauth_configured
IntegrationType:
  - aws_cloud_account
Query:
  Engine: CloudQL-v0.0.1
  ListOfTables:
    - aws_codebuild_project
    - aws_codebuild_source_credential
  Parameters: []
  PrimaryTable: aws_codebuild_project
  QueryToExecute: |
    SELECT
      p.arn AS resource,
      p.og_account_id AS og_account_id,
      p.og_resource_id AS og_resource_id,
      CASE
        WHEN p.source ->> 'Type' NOT IN ('GITHUB', 'BITBUCKET') THEN 'skip'
        WHEN c.auth_type = 'OAUTH' THEN 'ok'
        ELSE 'alarm'
      END AS status,
      CASE
        WHEN p.source ->> 'Type' = 'NO_SOURCE' THEN p.title || ' doesn''t have input source code.'
        WHEN p.source ->> 'Type' NOT IN ('GITHUB', 'BITBUCKET') THEN p.title || ' source code isn''t in GitHub/Bitbucket repository.'
        WHEN c.auth_type = 'OAUTH' THEN p.title || ' using OAuth to connect source repository.'
        ELSE p.title || ' not using OAuth to connect source repository.'
      END AS reason,
      p.region,
      p.account_id
    FROM
      aws_codebuild_project AS p
    LEFT JOIN aws_codebuild_source_credential AS c 
      ON (p.region = c.region AND p.source ->> 'Type' = c.server_type);
Severity: high
Tags:
  category:
    - Compliance
  cis_controls_v8_ig1:
    - "true"
  cisa_cyber_essentials:
    - "true"
  fedramp_low_rev_4:
    - "true"
  fedramp_moderate_rev_4:
    - "true"
  ffiec:
    - "true"
  hipaa_final_omnibus_security_rule_2013:
    - "true"
  hipaa_security_rule_2003:
    - "true"
  nist_800_53_rev_4:
    - "true"
  nist_csf:
    - "true"
  pci_dss_v321:
    - "true"
  plugin:
    - aws
  service:
    - AWS/CodeBuild
  soc_2:
    - "true"
Title: CodeBuild GitHub or Bitbucket source repository URLs should use OAuth