Title: "Find AWS CodeDeploy deployment configurations"
Description: "Allows users to query AWS CodeDeploy Deployment Configurations to retrieve information about the deployment configurations within AWS CodeDeploy service."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      arn,
      deployment_config_id,
      deployment_config_name,
      traffic_routing_config -> 'TimeBasedLinear' ->> 'LinearInterval' as linear_interval,
      traffic_routing_config -> 'TimeBasedLinear' ->> 'LinearPercentage' as linear_percentage
    from
      aws_codedeploy_deployment_config
    where
      traffic_routing_config ->> 'Type' = 'TimeBasedLinear';
Tags:
  cloud_asset_management:
  - "true"
  cloud_ops:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - CodeDeploy
