Title: "Find AWS EMR Security Configurations Details"
Description: "Allows users to query AWS EMR (Amazon Elastic MapReduce) Security Configurations. This table provides information about security settings and configurations that can be applied to EMR clusters, managing encryption, authentication, and authorization. These configurations are crucial for ensuring the secure handling of data, protecting sensitive information, and complying with various data security standards and regulations."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      creation_date_time,
      encryption_configuration,
      instance_metadata_service_configuration,
      security_configuration
    from
      aws_emr_security_configuration;
Tags:
  cloud_asset_management:
  - "true"
  cloud_data_security:
  - "true"
  cloud_identity_security:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - EMR
