Title: "List AWS Config Retention Configuration Details"
Description: "Allows users to query AWS Config Retention Configuration for information about the retention period that AWS Config uses to retain your configuration items."
Connectors:
- AWS
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      retention_period_in_days,
      title,
      region
    from
      aws_config_retention_configuration;
Tags:
  cloud_asset_management:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - AWS Config
