ID: aws_route53_resolver_query_log_config_1
Title: "Find Route 53 Resolver Query Log Configurations"
Description: "Allows users to query AWS Route 53 Resolver Query Log Configurations."
Connector:
- aws
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      id,
      arn,
      creation_time,
      share_status,
      status
    from
      aws_route53_resolver_query_log_config;
  PrimaryTable: null
  ListOfTables: []
  Parameters: []
Tags:
  cloud_asset_management:
  - "true"
  cloud_provider:
  - aws
  cloud_service:
  - Route 53
