ID: aws_sagemaker_endpoint_configuration_encryption_at_rest_enabled
Title: SageMaker endpoint configuration encryption should be enabled
Description: To help protect data at rest, ensure encryption with AWS Key Management Service (AWS KMS) is enabled for your SageMaker endpoint.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    select
      arn as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      case
        when kms_key_id is null then 'alarm'
        else 'ok'
      end as status,
      case
        when kms_key_id is null then title || ' encryption at rest disabled.'
        else title || ' encryption at rest enabled.'
      end as reason
      
      , region, account_id
    from
      aws_sagemaker_endpoint_configuration;
  PrimaryTable: aws_sagemaker_endpoint_configuration
  ListOfTables:
  - aws_sagemaker_endpoint_configuration
  Parameters: []
Connector:
- aws
Tags:
  category:
  - Compliance
  cisa_cyber_essentials:
  - "true"
  fedramp_low_rev_4:
  - "true"
  fedramp_moderate_rev_4:
  - "true"
  gdpr:
  - "true"
  gxp_21_cfr_part_11:
  - "true"
  gxp_eu_annex_11:
  - "true"
  hipaa_final_omnibus_security_rule_2013:
  - "true"
  hipaa_security_rule_2003:
  - "true"
  nist_800_171_rev_2:
  - "true"
  nist_800_53_rev_4:
  - "true"
  nist_800_53_rev_5:
  - "true"
  nist_csf:
  - "true"
  pci_dss_v321:
  - "true"
  plugin:
  - aws
  rbi_cyber_security:
  - "true"
  service:
  - AWS/SageMaker
  soc_2:
  - "true"
Severity: high
