ID: aws_elb_application_lb_desync_mitigation_mode
Title: ELB application load balancers should be configured with defensive or strictest desync mitigation mode
Description: This control checks whether an Application Load Balancer is configured with defensive or strictest desync mitigation mode. The control fails if an Application Load Balancer is not configured with defensive or strictest desync mitigation mode.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    with app_lb_desync_mitigation_mode as (
      select
        arn,
        l ->> 'Key',
        l ->> 'Value' as v
      from
        aws_ec2_application_load_balancer,
        jsonb_array_elements(load_balancer_attributes) as l
      where
        l ->> 'Key' = 'routing.http.desync_mitigation_mode'
    )
    select
      a.arn as resource,
      a.kaytu_account_id as kaytu_account_id,
      a.kaytu_resource_id as kaytu_resource_id,
      case
        when m.v = any(array['defensive', 'strictest']) then 'ok'
        else 'alarm'
      end as status,
        title || ' has ' || m.v || ' desync mitigation mode.' as reason
      
      , region, account_id
    from
      aws_ec2_application_load_balancer as a
      left join app_lb_desync_mitigation_mode as m on a.arn = m.arn;
  PrimaryTable: aws_ec2_application_load_balancer
  ListOfTables:
  - aws_ec2_application_load_balancer
  Parameters: []
Connector:
- aws
Tags:
  aws_foundational_security:
  - "true"
  category:
  - Compliance
  foundational_security_category:
  - data_integrity
  foundational_security_item_id:
  - elb_12
  plugin:
  - aws
  service:
  - AWS/ELB
Severity: medium
