ID: azure_application_insights_linked_to_log_analytics_workspace
Title: Azure Monitor Logs for Application Insights should be linked to a Log Analytics workspace
Description: Link the Application Insights component to a Log Analytics workspace for logs encryption. Customer-managed keys are commonly required to meet regulatory compliance and for more control over the access to your data in Azure Monitor. Linking your component to a Log Analytics workspace that's enabled with a customer-managed key, ensures that your Application Insights logs meet this compliance requirement, see https://docs.microsoft.com/azure/azure-monitor/platform/customer-managed-keys.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
        select
          a.id as resource,
          case
            when type = 'microsoft.insights/components' and workspace_resource_id is not null then 'ok'
            else 'alarm'
          end as status,
          case
            when type = 'microsoft.insights/components' and workspace_resource_id is not null then a.name || ' linked to log analytics workspace.'
            else a.name || ' not linked to log analytics workspace.'
          end as reason
          
          
          
        from
          azure_application_insight as a
          left join azure_subscription sub on sub.subscription_id = a.subscription_id;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- azure
Tags: {}
Severity: low
