ID: aws_backup_plan_region_configured
Title: Backup plan should exist in a region
Description: Ensure that there exists at least one backup plan in a region. The rule is non-compliant if there are no backup plans in a region.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    with count_plans as (
      select
        region,
        account_id,
        count(*) as count
      from
        aws_backup_plan
      group by
        region,
        account_id
    )
    select
      'arn:' || r.partition || '::' || r.region || ':' || r.account_id as resource,
      r.kaytu_account_id as kaytu_account_id,
      r.kaytu_resource_id as kaytu_resource_id,
      case
        when cp.count > 0 then 'ok'
        else 'alarm'
      end as status,
      case
        when cp.count > 0 then cp.count || ' backup plan(s) exist in region ' || r.region || '.'
        else 'No backup plans exist in region ' || r.region || '.'
      end as reason
    from
      aws_region as r
      left join count_plans as cp on r.account_id = cp.account_id and r.region = cp.region;
  PrimaryTable: aws_backup_plan
  ListOfTables:
  - aws_backup_plan
  - aws_region
  Parameters: []
Connector:
- aws
Tags: {}
Severity: low
