ID: azure_sql_db_active_directory_admin_configured
Title: "Ensure that Azure Active Directory Admin is configured"
Description: "Use Azure Active Directory Authentication for authentication with SQL Database."
Tags:
    category:
        - Compliance
    cis:
        - "true"
    cis_item_id:
        - "4.4"
    cis_level:
        - "1"
    cis_section_id:
        - "4"
    cis_type:
        - automated
    cis_version:
        - v1.3.0
    plugin:
        - azure
    service:
        - Azure/SQL
Query:
    Engine: odysseus-v0.0.1
    ListOfTables:
        - azure_ad_administrator
        - azure_sql_server
        - azure_subscription
    Parameters: []
    PrimaryTable: azure_sql_server
    QueryToExecute: "select\n  s.id as resource,\n  s.kaytu_account_id as kaytu_account_id,\n  s.kaytu_resource_id as kaytu_resource_id,\n  case\n    when server_azure_ad_administrator is null then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when server_azure_ad_administrator is null then name || ' Azure AD authentication not configured.'\n    else name || ' Azure AD authentication configured.'\n  end as reason\n  \n  , s.resource_group as resource_group\n  , sub.display_name as subscription\nfrom\n  azure_sql_server s,\n  azure_subscription sub\nwhere\n  sub.subscription_id = s.subscription_id;\n"
Severity: high
Connector:
    - Azure
