ID: azure_sql_server_va_setting_scan_reports_configured
Title: "Ensure that VA setting Send scan reports to is configured for a SQL server"
Description: "Configure 'Send scan reports to' with email ids of concerned data owners/stakeholders for a critical SQL servers."
Query:
    Engine: odysseus-v0.0.1
    ListOfTables:
        - azure_sql_server
        - azure_subscription
    Parameters: []
    PrimaryTable: azure_sql_server
    QueryToExecute: "select\n  s.id as resource,\n  s.kaytu_account_id as kaytu_account_id,\n  s.kaytu_resource_id as kaytu_resource_id,\n  case\n    when\n      security -> 'properties' ->> 'state' = 'Disabled'\n      or\n      (\n        security -> 'properties' ->> 'state' = 'Enabled'\n        and assessment -> 'properties' ->> 'storageContainerPath' is not null\n        and assessment -> 'properties' -> 'recurringScans' ->> 'emails' = '[]'\n      )\n      then 'alarm'\n    else 'ok'\n  end as status,\n  case\n    when\n      security -> 'properties' ->> 'state' = 'Disabled'\n      or\n      (\n        security -> 'properties' ->> 'state' = 'Enabled'\n        and assessment -> 'properties' ->> 'storageContainerPath' is not null\n        and assessment -> 'properties' -> 'recurringScans' ->> 'emails' = '[]'\n      )\n    then s.name || ' VA scan reports and alerts not configured send email.'\n    else s.name || ' VA scan reports and alerts configured to send email.'\n  end as reason\n  \n  , s.resource_group as resource_group\n  , sub.display_name as subscription\nfrom\n  azure_sql_server s,\n  jsonb_array_elements(server_security_alert_policy) security,\n  jsonb_array_elements(server_vulnerability_assessment) assessment,\n  azure_subscription sub\nwhere\n  sub.subscription_id = s.subscription_id;\n"
Severity: high
Tags:
    category:
        - Compliance
    cis:
        - "true"
    cis_item_id:
        - 4.2.4
    cis_level:
        - "2"
    cis_section_id:
        - "4.2"
    cis_type:
        - automated
    cis_version:
        - v1.3.0
    plugin:
        - azure
    service:
        - Azure/SQL
Connector:
    - Azure
