ID: azure_appservice_ftp_deployment_disabled
Title: "Ensure FTP deployments are disabled"
Description: "By default, Azure Functions, Web and API Services can be deployed over FTP. If FTP is required for an essential deployment workflow, FTPS should be required for FTP login for all App Service Apps and Functions."
Query:
    Engine: odysseus-v0.0.1
    ListOfTables:
        - azure_app_service_function_app
        - azure_app_service_web_app
        - azure_subscription
    Parameters: []
    PrimaryTable: null
    QueryToExecute: "select\n    fa.id as resource,\n    fa.kaytu_account_id as kaytu_account_id,\n    fa.kaytu_resource_id as kaytu_resource_id,\n    'azure_app_service_function_app' as kaytu_table_name,\n    case\n      when configuration -> 'properties' ->> 'ftpsState' = 'AllAllowed' then 'alarm'\n      else 'ok'\n    end as status,\n    case\n      when configuration -> 'properties' ->> 'ftpsState' = 'AllAllowed' then name || ' FTP deployments enabled.'\n      else name || ' FTP deployments disabled.'\n    end as reason\n  \n  , fa.resource_group as resource_group\n  , sub.display_name as subscription\n  from\n    azure_app_service_function_app fa,\n    azure_subscription sub\n  where\n    sub.subscription_id = fa.subscription_id\nunion\n  select\n    wa.id as resource,\n    wa.kaytu_account_id as kaytu_account_id,\n    wa.kaytu_resource_id as kaytu_resource_id,\n    'azure_app_service_web_app' as kaytu_table_name,\n    case\n      when configuration -> 'properties' ->> 'ftpsState' = 'AllAllowed' then 'alarm'\n      else 'ok'\n    end as status,\n    case\n      when configuration -> 'properties' ->> 'ftpsState' = 'AllAllowed' then name || ' FTP deployments enabled.'\n      else name || ' FTP deployments disabled.'\n    end as reason\n  \n  , wa.resource_group as resource_group\n  , sub.display_name as subscription\n  from\n    azure_app_service_web_app as wa,\n    azure_subscription as sub\n  where\n    sub.subscription_id = wa.subscription_id;\n"
Severity: medium
Tags:
    category:
        - Compliance
    cis:
        - "true"
    cis_item_id:
        - "9.10"
    cis_level:
        - "1"
    cis_section_id:
        - "9"
    cis_type:
        - automated
    cis_version:
        - v1.3.0
    plugin:
        - azure
    service:
        - Azure/AppService
Connector:
    - Azure
