ID: azure_compute_vm_allowlist_rules_in_adaptive_application_control_policy_updated
Title: "Allowlist rules in your adaptive application control policy should be updated"
Description: "Monitor for changes in behavior on groups of machines configured for auditing by Azure Security Center's adaptive application controls. Security Center uses machine learning to analyze the running processes on your machines and suggest a list of known-safe applications. These are presented as recommended apps to allow in adaptive application control policies."
Connector:
- azure
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      id as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      'info' as status,
      'Manual verification required.' as reason,
      display_name as subscription
    from
      azure_subscription;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Severity: low
Tags:
  manual-verification:
  - "true"
