ID: azure_compute_vm_scale_set_security_configuration_vulnerabilities_remediated
Title: Vulnerabilities in security configuration on your virtual machine scale sets should be remediated
Description: Audit the OS vulnerabilities on your virtual machine scale sets to protect them from attacks.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      id as resource,
      kaytu_account_id as kaytu_account_id,
      kaytu_resource_id as kaytu_resource_id,
      'info' as status,
      'Manual verification required. Check control description for more details.' as reason,
      display_name as subscription
    from
      azure_subscription;
  PrimaryTable: ""
  ListOfTables: []
  Parameters: []
Connector:
- azure
Tags:
  manual-verification: true
Severity: low
