ID: azure_sql_db_active_directory_admin_configured
Title: Ensure that Azure Active Directory Admin is configured
Description: Use Azure Active Directory Authentication for authentication with SQL Database.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    select
      s.id as resource,
      s.kaytu_account_id as kaytu_account_id,
      s.kaytu_resource_id as kaytu_resource_id,
      case
        when server_azure_ad_administrator is null then 'alarm'
        else 'ok'
      end as status,
      case
        when server_azure_ad_administrator is null then name || ' Azure AD authentication not configured.'
        else name || ' Azure AD authentication configured.'
      end as reason
      
      , s.resource_group as resource_group
      , sub.display_name as subscription
    from
      azure_sql_server s,
      azure_subscription sub
    where
      sub.subscription_id = s.subscription_id;
  PrimaryTable: azure_sql_server
  ListOfTables:
  - azure_ad_administrator
  - azure_sql_server
  - azure_subscription
  Parameters: []
Connector:
- azure
Tags:
  category:
  - Compliance
  cis:
  - "true"
  cis_item_id:
  - "4.4"
  cis_level:
  - "1"
  cis_section_id:
  - "4"
  cis_type:
  - automated
  cis_version:
  - v1.3.0
  plugin:
  - azure
  service:
  - Azure/SQL
Severity: high
