ID: azure_configure_audit_action_group_for_sql_server_auditing
Title: "Configure \"AuditActionGroup\" for SQL Server Auditing"
Description: "Ensure that \"AuditActionGroup\" property is well configured at the Azure SQL database server level."
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |
    select
      name as resource,
      s.og_resource_id,
      s.og_account_id,
      case
        when (select ARRAY_AGG(g) from jsonb_array_elements_text(ap -> 'properties' -> 'auditActionsAndGroups') as g) @> ARRAY['SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP','FAILED_DATABASE_AUTHENTICATION_GROUP','BATCH_COMPLETED_GROUP'] then 'ok'
        else 'alarm'
      end as status,
      case
        when (select ARRAY_AGG(g) from jsonb_array_elements_text(ap -> 'properties' -> 'auditActionsAndGroups') as g) @> ARRAY['SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP','FAILED_DATABASE_AUTHENTICATION_GROUP','BATCH_COMPLETED_GROUP'] then 'AuditActionGroup property configuration for the selected Microsoft Azure SQL database server is compliant'
        else 'AuditActionGroup property configuration for the selected Microsoft Azure SQL database server is not compliant'
      end as reason,
      resource_group as resource_group,
      sub.display_name as subscription
    from
      azure_sql_server as s
      left join azure_subscription as sub on s.subscription_id = sub.subscription_id,
      jsonb_array_elements(server_audit_policy) as ap
  PrimaryTable: azure_sql_server
  ListOfTables:
    - azure_sql_server
    - azure_subscription
  Parameters: []
Severity: medium
Tags:
  platform_score_cloud_service_name:
    - Azure Managed SQL Service
  score_service_name:
    - Azure Managed SQL Service
Integration_Type_Name:
  - azure_subscription
