ID: azure_insight_compute_availability_set_without_managed_disk_configuration
Title: "AV Sets with Legacy Disks"
Description: "List of availability sets which does not use managed disks configuration"
Connector:
- azure
Query:
  ID: ""
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      name,
      sku_name, subscription_id, kaytu_account_id, kaytu_resource_id
    from
      azure_compute_availability_set
    where
      sku_name = 'Classic';
  PrimaryTable: azure_compute_availability_set
  ListOfTables:
  - azure_compute_availability_set
  Parameters: []
Tags:
  category:
  - Security
  - Technical Debt
  - Resiliency
  - Cost Management
