ID: azure_app_configuration_sku_standard
Title: App Configuration should use standard SKU
Description: Ensure that App Configuration uses standard SKU tier. This control is non-compliant if App Configuration does not use standard SKU.
Query:
  Engine: odysseus-v0.0.1
  QueryToExecute: |-
    select
      a.id as resource,
      a.kaytu_account_id as kaytu_account_id,
      a.kaytu_resource_id as kaytu_resource_id,
      case
        when sku_name = 'standard' then 'ok'
        else 'alarm'
      end as status,
        a.name || ' has ' || sku_name || ' SKU tier.' as reason
    from
      azure_app_configuration as a,
      azure_subscription as sub;
  PrimaryTable: azure_app_configuration
  ListOfTables:
  - azure_app_configuration
  - azure_subscription
  Parameters: []
Connector:
- azure
Tags: {}
Severity: low
